# -*- coding: utf-8 -*-

"""
    mundiapilib.models.create_credit_card_payment_request

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import mundiapilib.models.create_credit_card_request

class CreateCreditCardPaymentRequest(object):

    """Implementation of the 'CreateCreditCardPaymentRequest' model.

    The settings for creating a credit card payment

    Attributes:
        installments (int): Number of installments
        statement_descriptor (string): The text that will be shown on the
            credit card's statement
        credit_card_info (CreateCreditCardRequest): Credit card data
        retries (int): Number of retries
        update_subscription_card (bool): Indicates if the card from the
            subscription must be updated
        credit_card_id (string): The credit card id
        capture (bool): Indicates if the operation should be only
            authorization or auth and capture.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "installments" : "installments",
        "statement_descriptor" : "statement_descriptor",
        "credit_card_info" : "credit_card_info",
        "retries" : "retries",
        "update_subscription_card" : "update_subscription_card",
        "credit_card_id" : "credit_card_id",
        "capture" : "capture"
    }

    def __init__(self,
                 installments=1,
                 statement_descriptor=None,
                 credit_card_info=None,
                 retries=None,
                 update_subscription_card=None,
                 credit_card_id=None,
                 capture=True):
        """Constructor for the CreateCreditCardPaymentRequest class"""

        # Initialize members of the class
        self.installments = installments
        self.statement_descriptor = statement_descriptor
        self.credit_card_info = credit_card_info
        self.retries = retries
        self.update_subscription_card = update_subscription_card
        self.credit_card_id = credit_card_id
        self.capture = capture


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        installments = dictionary.get("installments") if dictionary.get("installments") else 1
        statement_descriptor = dictionary.get("statement_descriptor")
        credit_card_info = mundiapilib.models.create_credit_card_request.CreateCreditCardRequest.from_dictionary(dictionary.get("credit_card_info")) if dictionary.get("credit_card_info") else None
        retries = dictionary.get("retries")
        update_subscription_card = dictionary.get("update_subscription_card")
        credit_card_id = dictionary.get("credit_card_id")
        capture = dictionary.get("capture") if dictionary.get("capture") else True

        # Return an object of this model
        return cls(installments,
                   statement_descriptor,
                   credit_card_info,
                   retries,
                   update_subscription_card,
                   credit_card_id,
                   capture)


