# -*- coding: utf-8 -*-

"""
    mundiapilib.models.create_charge_request

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
from mundiapilib.api_helper import APIHelper
import mundiapilib.models.create_customer_request
import mundiapilib.models.create_payment_request

class CreateChargeRequest():

    """Implementation of the 'CreateChargeRequest' model.

    Request for creating a new charge

    Attributes:
        code (string): Code
        amount (int): The amount of the charge, in cents
        due_at (datetime): The charge due date
        customer_id (string): The customer's id
        customer (CreateCustomerRequest): Customer data
        payment (CreatePaymentRequest): Payment data
        metadata (dict<object, string>): Metadata

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "code" : "code",
        "amount" : "amount",
        "due_at" : "due_at",
        "customer_id" : "customer_id",
        "customer" : "customer",
        "payment" : "payment",
        "metadata" : "metadata"
    }

    def __init__(self,
                 code=None,
                 amount=None,
                 due_at=None,
                 customer_id=None,
                 customer=None,
                 payment=None,
                 metadata=None):
        """Constructor for the CreateChargeRequest class"""

        # Initialize members of the class
        self.code = code
        self.amount = amount
        self.due_at = APIHelper.RFC3339DateTime(due_at) if due_at else None
        self.customer_id = customer_id
        self.customer = customer
        self.payment = payment
        self.metadata = metadata


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        code = dictionary.get("code")
        amount = dictionary.get("amount")
        due_at = APIHelper.RFC3339DateTime.from_value(dictionary.get("due_at")).datetime if dictionary.get("due_at") else None
        customer_id = dictionary.get("customer_id")
        customer = mundiapilib.models.create_customer_request.CreateCustomerRequest.from_dictionary(dictionary.get("customer")) if dictionary.get("customer") else None
        payment = mundiapilib.models.create_payment_request.CreatePaymentRequest.from_dictionary(dictionary.get("payment")) if dictionary.get("payment") else None
        metadata = dictionary.get("metadata")
        # Return an object of this model
        return cls(code,
                   amount,
                   due_at,
                   customer_id,
                   customer,
                   payment,
                   metadata)


