# -*- coding: utf-8 -*-

"""
    mundiapilib.models.create_customer_request

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import mundiapilib.models.create_address_request

class CreateCustomerRequest(object):

    """Implementation of the 'CreateCustomerRequest' model.

    Request for creating a new customer

    Attributes:
        name (string): Name
        email (string): Email
        phone (string): Phone number. Only numbers, no special characters.
        document (string): Document number. Only numbers, no special
            characters.
        person_type (string): Person type. Can be either 'person' or
            'company'
        address (CreateAddressRequest): The customer's address
        metadata (dict<object, string>): Metadata

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name" : "name",
        "email" : "email",
        "phone" : "phone",
        "document" : "document",
        "person_type" : "person_type",
        "address" : "address",
        "metadata" : "metadata"
    }

    def __init__(self,
                 name=None,
                 email=None,
                 phone=None,
                 document=None,
                 person_type=None,
                 address=None,
                 metadata=None):
        """Constructor for the CreateCustomerRequest class"""

        # Initialize members of the class
        self.name = name
        self.email = email
        self.phone = phone
        self.document = document
        self.person_type = person_type
        self.address = address
        self.metadata = metadata


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get("name")
        email = dictionary.get("email")
        phone = dictionary.get("phone")
        document = dictionary.get("document")
        person_type = dictionary.get("person_type")
        address = mundiapilib.models.create_address_request.CreateAddressRequest.from_dictionary(dictionary.get("address")) if dictionary.get("address") else None
        metadata = dictionary.get("metadata")

        # Return an object of this model
        return cls(name,
                   email,
                   phone,
                   document,
                   person_type,
                   address,
                   metadata)


