# -*- coding: utf-8 -*-

"""
    mundiapilib.models.create_capture_charge_request

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""


class CreateCaptureChargeRequest(object):

    """Implementation of the 'CreateCaptureChargeRequest' model.

    Request for capturing a charge

    Attributes:
        amount (int): The amount that will be captured

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "amount" : "amount"
    }

    def __init__(self,
                 amount=None):
        """Constructor for the CreateCaptureChargeRequest class"""

        # Initialize members of the class
        self.amount = amount


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        amount = dictionary.get("amount")

        # Return an object of this model
        return cls(amount)


