# -*- coding: utf-8 -*-

"""
    mundiapilib.models.update_subscription_credit_card_request

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import mundiapilib.models.create_credit_card_request

class UpdateSubscriptionCreditCardRequest(object):

    """Implementation of the 'UpdateSubscriptionCreditCardRequest' model.

    Request for updating the credit card from a subscription

    Attributes:
        credit_card (CreateCreditCardRequest): Credit card data
        credit_card_id (string): Credit card id
        credit_card_gateway_id (string): Credit card gateway id

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "credit_card" : "credit_card",
        "credit_card_id" : "credit_card_id",
        "credit_card_gateway_id" : "credit_card_gateway_id"
    }

    def __init__(self,
                 credit_card=None,
                 credit_card_id=None,
                 credit_card_gateway_id=None):
        """Constructor for the UpdateSubscriptionCreditCardRequest class"""

        # Initialize members of the class
        self.credit_card = credit_card
        self.credit_card_id = credit_card_id
        self.credit_card_gateway_id = credit_card_gateway_id


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        credit_card = mundiapilib.models.create_credit_card_request.CreateCreditCardRequest.from_dictionary(dictionary.get("credit_card")) if dictionary.get("credit_card") else None
        credit_card_id = dictionary.get("credit_card_id")
        credit_card_gateway_id = dictionary.get("credit_card_gateway_id")

        # Return an object of this model
        return cls(credit_card,
                   credit_card_id,
                   credit_card_gateway_id)


