# -*- coding: utf-8 -*-

"""
    mundiapilib.models.update_charge_credit_card_request

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import mundiapilib.models.create_credit_card_request

class UpdateChargeCreditCardRequest(object):

    """Implementation of the 'UpdateChargeCreditCardRequest' model.

    Request for updating credit card data

    Attributes:
        update_subscription (bool): Indicates if the subscriptions using this
            card must also be updated
        credit_card_id (string): Credit card id
        credit_card_gateway_id (string): Credit card id on the gateway
        credit_card (CreateCreditCardRequest): Credit card data

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "update_subscription" : "update_subscription",
        "credit_card_id" : "credit_card_id",
        "credit_card_gateway_id" : "credit_card_gateway_id",
        "credit_card" : "credit_card"
    }

    def __init__(self,
                 update_subscription=None,
                 credit_card_id=None,
                 credit_card_gateway_id=None,
                 credit_card=None):
        """Constructor for the UpdateChargeCreditCardRequest class"""

        # Initialize members of the class
        self.update_subscription = update_subscription
        self.credit_card_id = credit_card_id
        self.credit_card_gateway_id = credit_card_gateway_id
        self.credit_card = credit_card


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        update_subscription = dictionary.get("update_subscription")
        credit_card_id = dictionary.get("credit_card_id")
        credit_card_gateway_id = dictionary.get("credit_card_gateway_id")
        credit_card = mundiapilib.models.create_credit_card_request.CreateCreditCardRequest.from_dictionary(dictionary.get("credit_card")) if dictionary.get("credit_card") else None

        # Return an object of this model
        return cls(update_subscription,
                   credit_card_id,
                   credit_card_gateway_id,
                   credit_card)


