# -*- coding: utf-8 -*-

"""
    mundiapilib.mundi_api_client

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from .decorators import lazy_property
from .controllers.charges_controller import ChargesController
from .controllers.customers_controller import CustomersController
from .controllers.subscriptions_controller import SubscriptionsController
from .controllers.plans_controller import PlansController
from .controllers.invoices_controller import InvoicesController
from .controllers.orders_controller import OrdersController
from .configuration import Configuration

class MundiAPIClient(object):

    @lazy_property
    def charges(self):
        return ChargesController()

    @lazy_property
    def customers(self):
        return CustomersController()

    @lazy_property
    def subscriptions(self):
        return SubscriptionsController()

    @lazy_property
    def plans(self):
        return PlansController()

    @lazy_property
    def invoices(self):
        return InvoicesController()

    @lazy_property
    def orders(self):
        return OrdersController()


    def __init__(self, 
                 basic_auth_user_name = None,
                 basic_auth_password = None):
        if basic_auth_user_name != None:
            Configuration.basic_auth_user_name = basic_auth_user_name
        if basic_auth_password != None:
            Configuration.basic_auth_password = basic_auth_password


